// Generated by gencpp from file ball_casher/DriveToTarget.msg
// DO NOT EDIT!


#ifndef BALL_CASHER_MESSAGE_DRIVETOTARGET_H
#define BALL_CASHER_MESSAGE_DRIVETOTARGET_H

#include <ros/service_traits.h>


#include <ball_casher/DriveToTargetRequest.h>
#include <ball_casher/DriveToTargetResponse.h>


namespace ball_casher
{

struct DriveToTarget
{

typedef DriveToTargetRequest Request;
typedef DriveToTargetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DriveToTarget
} // namespace ball_casher


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ball_casher::DriveToTarget > {
  static const char* value()
  {
    return "c8652349d2a34a90a09475339e2a93d9";
  }

  static const char* value(const ::ball_casher::DriveToTarget&) { return value(); }
};

template<>
struct DataType< ::ball_casher::DriveToTarget > {
  static const char* value()
  {
    return "ball_casher/DriveToTarget";
  }

  static const char* value(const ::ball_casher::DriveToTarget&) { return value(); }
};


// service_traits::MD5Sum< ::ball_casher::DriveToTargetRequest> should match 
// service_traits::MD5Sum< ::ball_casher::DriveToTarget > 
template<>
struct MD5Sum< ::ball_casher::DriveToTargetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ball_casher::DriveToTarget >::value();
  }
  static const char* value(const ::ball_casher::DriveToTargetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ball_casher::DriveToTargetRequest> should match 
// service_traits::DataType< ::ball_casher::DriveToTarget > 
template<>
struct DataType< ::ball_casher::DriveToTargetRequest>
{
  static const char* value()
  {
    return DataType< ::ball_casher::DriveToTarget >::value();
  }
  static const char* value(const ::ball_casher::DriveToTargetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ball_casher::DriveToTargetResponse> should match 
// service_traits::MD5Sum< ::ball_casher::DriveToTarget > 
template<>
struct MD5Sum< ::ball_casher::DriveToTargetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ball_casher::DriveToTarget >::value();
  }
  static const char* value(const ::ball_casher::DriveToTargetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ball_casher::DriveToTargetResponse> should match 
// service_traits::DataType< ::ball_casher::DriveToTarget > 
template<>
struct DataType< ::ball_casher::DriveToTargetResponse>
{
  static const char* value()
  {
    return DataType< ::ball_casher::DriveToTarget >::value();
  }
  static const char* value(const ::ball_casher::DriveToTargetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BALL_CASHER_MESSAGE_DRIVETOTARGET_H
